name: kyra

services:
   kyra:
      build:
         context: .
         dockerfile: Dockerfile
         target: combined
      ports:
         - '3000:3000'
         - '4000:4000'
      environment:
         DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
         DATABASE_SCHEMA_EXPOSE: api,auth,private,public
      volumes:
         - ./test/schema:/app/kyra/schema
         - ./test/migrations:/app/kyra/migrations
         - ./test/seeds:/app/kyra/seeds
         - ./test/types:/app/kyra/types
      depends_on:
         postgres:
            condition: service_healthy
      networks:
         - kyra-network

   postgres:
      image: postgres:17.4
      ports:
         - 5432:5432
      environment:
         POSTGRES_PASSWORD: postgres
         POSTGRES_USER: postgres
         POSTGRES_DB: postgres
      volumes:
         - postgres_data:/var/lib/postgresql/data
      healthcheck:
         test: ['CMD-SHELL', 'pg_isready -U postgres']
         interval: 2s
         timeout: 5s
         retries: 10
      networks:
         - kyra-network

volumes:
   postgres_data:

networks:
   kyra-network:
      driver: bridge
